[build]
  publish = "."

[[redirects]]
from = "https://www.incheongo.co.kr/*"
to = "https://incheongo.co.kr/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
