[build]
  publish = "."

[[redirects]]
  from = "https://www.도메인/*"
  to = "https://도메인/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
